import jwt from "jsonwebtoken";

export const authmiddleware =  async(req,res,next)=>{
    try {
        const varifiedToken = req.headers.token;
        console.log(varifiedToken);        
        if(!varifiedToken) return res.status(404).json({wrn: "Invalid Token"});

        //This middleware verify the user, wheter it is sign in or not, It verify the user using token generated by user sign in.
        const isVarifiedUser = await jwt.verify(varifiedToken,"abcdefg692354%#$^8*");
        if(!isVarifiedUser) return res.status(404).json({wrn:"User not authorized"});
            req.user = isVarifiedUser;

            // if(req.user.isadmin === "admin") next(); // User for Different role to sign in like As a admin, or as a user

            next();
    } catch (error) {
        console.log("error",error)
    }
}
